name: Java CI

on:
  schedule:
    - cron: "0 1 * * *"  # Runs every day at 1:00 AM UTC ( 7:00 AM UTC+6 )
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml  # Skip tests during build

      - name: Ensure Downloads Directory Exists
        run: mkdir -p $GITHUB_WORKSPACE/downloads

      - name: Run Cucumber tests with JUnit
        run: mvn -B test -Dtest=runners.TestRunner
        continue-on-error: true  # Continue even if tests fail
